paginate: 12
paginate_path: /posts/:num/
plugins:
  - jekyll-paginate
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
exclude:
  - docker-compose.yml
  - Dockerfile
  - run-gh-pages.bat
  - samples/
